language: objective-c
osx_image: xcode11.3

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/LayoutInspectorExample.xcworkspace -scheme LayoutInspectorExample -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11" -UseModernBuildSystem=YES test
- pod lib lint
